apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    service: backend
  name: backend-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      service: backend
  strategy: {"RollingUpdate"}
  template:
    metadata:
      labels:
        service: backend
    spec:
      containers:
      - name: backend-pod
        ports:
        - containerPort: 5000
        env:
          - name: DATABASE_URL
            value:  postgresql://postgres:password@db-service:5432/guests_db
        image: backend
        imagePullPolicy: Never

      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
      service: backend
  name: backend-service
spec:
  type: LoadBalancer
  ports:
    - name: "5000"
      port: 8000
      targetPort: 5000
  selector:
    service: backend
